spring:
  data:
    mongodb:
      # The full connection string from your Java code
      uri: mongodb+srv://kavya:kkaavvyyaa@cluster0.niiwvsc.mongodb.net/journaldb?appName=Cluster0
      # Replaces your getDatabaseName() method
      database: journaldb
      # Replaces your autoIndexCreation() override
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: add email through which you want to send email
    password: add app password here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# adding logging level in yml file
logging:
  level:
    org.springframework.data.mongodb: DEBUG

# adding root, this will affect entire package and will show only error logs
#logging:
#    level:
#      root: ERROR

# turning off logging for particular package
#logging:
#    level:
#      com.Journal.journalDemo.service: OFF

weather:
  api:
    key: ae2e15d03b62f26ddb6cb4ad9f165e81
